### ISSUE TITLE
找不到avbot.sln

### ISSUE THREAD

**Issue by KiritoStudio** [avplayer/avbot#45]
这是新版之后不提供Windows的编译了喵？还是忘记了喵？
btw：请问bot占用内存多大？

**Comment by microcai** [comment]
windows 版本可从这里下载 ftp://ci.avplayer.org/

**Comment by KiritoStudio** [comment]
@microcai 感谢回复，但是我想要自己加一些功能，但是看了下你版本的介绍，是不支持自定义一些功能的，所以我想自己加，btw，我想要加一些C#的代码，实现一些自己的功能，比如查当前ip啦，小玩意儿。。。

**Comment by microcai** [comment]
查 ip 的模块有内置的.

**Comment by microcai** [comment]
自定义功能可以写 DLL  插件

**Comment by KiritoStudio** [comment]
都只能用C++吗？还有。。怎么写。。有没有demo？

**Comment by microcai** [comment]
DLL 很简单的, 导出一个 avbot_on_message2 函数即可.类型是
```
void  avbot_on_message2(const char * speaker,const char * message, const char * channel, message_sender_t sender, void* _apitag);
```

内部使用 
```
sender("消息", _apitag) 
```

 来发送

sender 的类型是 

	typedef void (*message_sender_t)(const char * message, void* _apitag);

**Comment by microcai** [comment]
C# 应该也可以导出 函数给外部调用的吧.

**Comment by microcai** [comment]
写了一个wiki 
https://wiki.avplayer.org/avbot_extension

**Comment by KiritoStudio** [comment]
查询了一下，
1.C#应该是不能用C++这类导出函数的方式来调用C#的，不知道是不是可以加入 http://cool8511.blog.hexun.com/36592218_d.html 这样的方式来支持C#的拓展的编写。判断.net的dll的话，应该可以用PE头来判断。
2.不是太了解C++，想确认的是C#的程序是能调用到 typedef void (*message_sender_t)(const char * message, void* _apitag);这个方法的吧。。

**Comment by microcai** [comment]
on Thursday 08 January 2015 23:43:59，Xin wrote：
> 查询了一下，
> 1.C#应该是不能用C++这类导出函数的方式来调用C#的，不知道是不是可以加入
> http://cool8511.blog.hexun.com/36592218_d.html
> 这样的方式来支持C#的拓展的编写。判断.net的dll的话，应该可以用PE头来判断。 2.不是太了解C++，想确认的是C#的程序是能调用到
> typedef void (*message_sender_t)(const char * message, void*
> _apitag);这个方法的吧。。

这样会比较麻烦, avbot 需要在没有安装 .net 的机器上运行, 所以不能直接支持 c# 

你可以C++编写一个中间 DLL, 然后再调用你 c# 写的 dll.

**Comment by KiritoStudio** [comment]
看来还是自己造轮子好。。

**Comment by whyb** [comment]
@microcai @KiritoStudio 想要C#和C++相互调用callback的话，用C++/CLR吧。。。
