### ISSUE TITLE
只想要群记录功能，并能发不出网址供查询，

### ISSUE THREAD

**Issue by talway** [avplayer/avbot#49]
只想要群记录功能，并能发出网址供查询，

限制的编译安装，太难了，能否简化或一键安装，最好是cetos6.6平台的，

麻烦能否简化安装，

谢谢

已试了10多次 没一次成功的

**Comment by microcai** [comment]
centos 下编译纯自虐,好自为之.

**Comment by talway** [comment]
能否提示下 在哪里编译好，

**Comment by kikidong** [comment]
ARCH LINUX/GENTOO LINUX


2015-08-25 22:56 GMT+08:00 talway <notifications@github.com>:
